### ISSUE TITLE
Proton-exp community build does not show up in Steam

### ISSUE THREAD

**Issue by mgidding** [flathub/com.valvesoftware.Steam.CompatibilityTool.Proton-Exp#23]
Hi,

I have the Proton community build, Proton-GE community build and Proton experimental community builds all installed. However, while the former two show up in my Flatpak steam client, Proton experimental does not. How can I make it show up? I have tried uninstalling the regular Proton community build (perhaps there was a conflict) but that did not help.

```
Proton (community build)                          com.valvesoftware.Steam.CompatibilityTool.Proton                 6.3-2                            beta               flathub-beta             user

Proton experimental (community build)             com.valvesoftware.Steam.CompatibilityTool.Proton-Exp             6.3-20210429                     stable             flathub                  user

Proton-GE (community build)                       com.valvesoftware.Steam.CompatibilityTool.Proton-GE              6.5-GE-3                         beta               flathub-beta             user
```

**Comment by gasinvein** [comment]
Looks like you're running Steam flatpak `beta` branch - it picks up only `beta` extensions.

**Comment by mgidding** [comment]
I can confirm that switching to the stable branch solved my problem. Thank you!
