### ISSUE TITLE
Update to 5.13-20210217?

### ISSUE THREAD

**Issue by dustContributor** [flathub/com.valvesoftware.Steam.CompatibilityTool.Proton-Exp#4]
Hi! Could this be updated for 5.13-20210217? This update is particularly interesting since it has the futex2 patches available for testing.

Thank you for your time!

**Comment by gasinvein** [comment]
I'm afraid it will suffer from the same network issue as https://github.com/flathub/com.valvesoftware.Steam.CompatibilityTool.Proton/issues/40#issuecomment-780764823

**Comment by gasinvein** [comment]
Fixed by #5
